/** @type {import('tailwindcss').Config} */
module.exports = {
  darkMode: 'class',
  content: ['./pages/**/*.{js,ts,jsx,tsx}', './components/**/*.{js,ts,jsx,tsx}'],
  theme: {
    extend: {
      colors: {
        background: '#0b1326',
        surface: '#0b1326',
        'surface-charcoal': '#111827',
        'surface-dim': '#0b1326',
        'surface-bright': '#31394e',
        'surface-container-lowest': '#060d20',
        'surface-container-low': '#131b2e',
        'surface-container': '#171f33',
        'surface-container-high': '#222a3e',
        'surface-container-highest': '#2d3449',
        'surface-elevated': '#1F2937',
        'surface-variant': '#2d3449',
        'surface-tint': '#4edea3',
        primary: '#4edea3',
        'primary-container': '#10b981',
        'primary-fixed': '#6ffbbe',
        'primary-fixed-dim': '#4edea3',
        'on-primary': '#003824',
        'on-primary-container': '#00422b',
        'on-primary-fixed': '#002113',
        'on-primary-fixed-variant': '#005236',
        'inverse-primary': '#006c49',
        secondary: '#b7c8e1',
        'secondary-container': '#3a4a5f',
        'secondary-fixed': '#d3e4fe',
        'secondary-fixed-dim': '#b7c8e1',
        'on-secondary': '#213145',
        'on-secondary-container': '#a9bad3',
        'on-secondary-fixed': '#0b1c30',
        'on-secondary-fixed-variant': '#38485d',
        tertiary: '#b3cdb7',
        'tertiary-container': '#8fa994',
        'tertiary-fixed': '#cee9d3',
        'tertiary-fixed-dim': '#b3cdb7',
        'on-tertiary': '#1f3526',
        'on-tertiary-container': '#273e2e',
        'on-tertiary-fixed': '#092012',
        'on-tertiary-fixed-variant': '#354c3b',
        error: '#ffb4ab',
        'error-container': '#93000a',
        'on-error': '#690005',
        'on-error-container': '#ffdad6',
        'text-primary': '#F1F5F9',
        'text-secondary': '#94A3B8',
        'text-high-contrast': '#D8F3DC',
        'on-surface': '#dbe2fd',
        'on-surface-variant': '#bbcabf',
        'on-background': '#dbe2fd',
        'inverse-surface': '#dbe2fd',
        'inverse-on-surface': '#283044',
        outline: '#86948a',
        'outline-variant': '#3c4a42',
        'border-subtle': '#334155',
        'border-glass': 'rgba(216, 243, 220, 0.1)',
        'emerald-accent': '#4edea3',
        'sapphire-deep': '#2a427a',
        'amethyst-muted': '#5a4d7a',
        'slate-teal': '#3d5a5c',
      },
      spacing: {
        'margin-desktop': '2.5rem',
        'margin-mobile': '1rem',
        'metadata-gap': '0.5rem',
        'gutter-sm': '1rem',
        'container-padding': '1.5rem',
      },
      fontFamily: {
        mono: ['JetBrains Mono', 'monospace'],
        sans: ['Hanken Grotesk', 'system-ui', 'sans-serif'],
        'body-md': ['JetBrains Mono', 'monospace'],
        'body-lg': ['JetBrains Mono', 'monospace'],
        'editorial-h1': ['JetBrains Mono', 'monospace'],
        'micro-metadata': ['JetBrains Mono', 'monospace'],
        'headline-xl': ['JetBrains Mono', 'monospace'],
        'label-sm': ['JetBrains Mono', 'monospace'],
        'headline-lg': ['JetBrains Mono', 'monospace'],
      },
      fontSize: {
        'headline-xl': ['40px', { lineHeight: '48px', letterSpacing: '-0.02em', fontWeight: '700' }],
        'headline-lg': ['32px', { lineHeight: '40px', letterSpacing: '-0.01em', fontWeight: '600' }],
        'headline-md': ['24px', { lineHeight: '32px', fontWeight: '500' }],
        'editorial-h1': ['24px', { lineHeight: '32px', letterSpacing: '0.02em', fontWeight: '600' }],
        'body-lg': ['18px', { lineHeight: '28px', fontWeight: '400' }],
        'body-md': ['16px', { lineHeight: '24px', fontWeight: '400' }],
        'body-sm': ['14px', { lineHeight: '20px', fontWeight: '400' }],
        'micro-metadata': ['11px', { lineHeight: '14px', letterSpacing: '0.08em', fontWeight: '500' }],
        'label-md': ['14px', { lineHeight: '20px', letterSpacing: '0.05em', fontWeight: '600' }],
        'label-sm': ['12px', { lineHeight: '16px', letterSpacing: '0.05em', fontWeight: '600' }],
      },
      borderRadius: { DEFAULT: '0.125rem', lg: '0.25rem', xl: '0.5rem', full: '0.75rem' },
      boxShadow: {
        hard: '4px 4px 0px #060e20',
        glow: 'inset 0 0 4px rgba(16, 185, 129, 0.3)',
        'glow-strong': 'inset 0 0 8px rgba(16, 185, 129, 0.5)',
      },
      animation: {
        'pulse-slow': 'pulse 3s ease-in-out infinite',
        'fade-in': 'fadeIn 0.5s ease-out',
        'slide-up': 'slideUp 0.5s ease-out',
        'glow-border': 'glowBorder 2s ease-in-out infinite',
      },
      keyframes: {
        fadeIn: { '0%': { opacity: '0' }, '100%': { opacity: '1' } },
        slideUp: { '0%': { opacity: '0', transform: 'translateY(20px)' }, '100%': { opacity: '1', transform: 'translateY(0)' } },
        glowBorder: { '0%, 100%': { boxShadow: 'inset 0 0 4px rgba(16, 185, 129, 0.2)' }, '50%': { boxShadow: 'inset 0 0 8px rgba(16, 185, 129, 0.5)' } },
      },
    },
  },
  plugins: [],
}
